version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
